version: '{build}'

clone_depth: 50

environment:
  matrix:
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.7.0
      MAVEN_OPTS: -Dhttps.protocols=TLSv1.2
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.7.0
      MAVEN_OPTS: -Dhttps.protocols=TLSv1.2
    - platform: x86
      JAVA_HOME: ${ProgramFiles(x86)}\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk1.8.0
    - platform: x64
      JAVA_HOME: $(ProgramFiles)\Java\jdk11

before_build:
  - cmd: java -Xmx32m -version
  - cmd: javac -J-Xmx32m -version
  - cmd: mvn -version

build_script:
  - mvn clean verify -V
