language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: openjdk6
      maven:
        version: 3.2.5
    - os: osx

addons:
  apt:
    packages:
      - openjdk-6-jdk
