language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk7
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: openjdk6
    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install maven; fi;
